theme = "onedark"

[editor]
line-number = "relative"
color-modes = true
mouse = true
cursorline = true
cursorcolumn = true
# Resolve true color detection problems (e.g. on Linux in Windows WSL2)
# such as the error, "theme: theme requires true color support".
true-color = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
0   = "goto_line_start"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0   = "goto_line_start"

[editor.whitespace]
render = "all"
# or control each character
# [editor.whitespace.render]
# space = "all"
# tab = "all"
# newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)
[editor.soft-wrap]
enable = true
max-wrap = 2
# max-indent-retain = 0
wrap-indicator = ""
wrap-at-text-width = false

